### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by michal-gubricky** [SovereignCloudStack/openstack-csp-helper#4]
The chart name is set to `csp-helper-chart` and this is different from the name, which is referenced in docs. Also when you run the command `helm package .`  it will by default generate a name like this `<chart-name>-<version>`.  I would suggest making naming consistent, so rename the chart name to `openstack-csp-helper`.

**Comment by eigenpaul** [comment]
Closed with [release 0.6.0](https://github.com/SovereignCloudStack/openstack-csp-helper/releases/tag/v0.6.0)
